### ISSUE TITLE
It's just a VIRUS, DO NOT INSTALL IT!

### ISSUE THREAD

**Issue by sleep2death** [chocolatey/boxstarter#397] opened 2019-05-02 04:06 UTC
It cames from my installation of "nodejs 10.13.0" msi file without any OBIOUS PROMPT!
It F**CKING RESTART  my comupter without any prompt!
It F**CKING BROKE my administrator privileges after restart!
And guess what, It's hard to UNINSTALL both from windows or choco!

**Comment by flcdrg** [comment] 2019-05-02 04:11
Duplicate of #371.

**Closed by flcdrg** 2019-05-02 04:11 UTC
Labels: Duplicate Issue

**Comment by gep13** [comment] 2019-05-02 06:09
@sleep2death thank you for reaching out.  While I can appreciate that you may be frustrated, I would ask that you don't use language like that when raising an issue here, there is simply no need for it.

**NOTE:** I have removed the offending words from your original post.

Let's start with the basic....

Boxstarter is not a virus.  It provides a mechanism to reliably and repeatably, perform a series of installations on your machine, and we like to think that it does this very well.

Hopefully you will have had a chance to read through the duplicate issue pointed out by @flcdrg as well as the linked issues to the Node JS issues.  Almost all of the issues that came out of decisions that were made to include Boxstarter in the Node JS installer have been addressed.

**Comment by sleep2death** [comment] 2019-05-02 08:30
@gep13 First of all, I love nodejs and its community, but the installation with the "Boxstarter" was such a pain. There are so many Serious safty complains and issues about the "boxstarter". I just lost my 15 minutes of the work because of the "restart". 

Sorry for the offending words I posted, but I will keep telling people stay away from this project before these issues are fixed.

**Comment by flcdrg** [comment] 2019-05-02 09:11
Boxstarter is just a tool. It's not perfect but it does what it does pretty well. The real issue here in my opinion was the Node installer trying to use Boxstarter in an unconventional way, and possibly with not enough testing before it was released publicly.

Don't blame Boxstarter for that.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by gep13** [comment] 2019-05-02 19:44
>@sleep2death said...
but I will keep telling people stay away from this project before these issues are fixed.

Before doing that, I would encourage you to try Boxstarter out in isolation first.  As @flcdrg points out, a lot of the issues that you are referring to came from the "way" that Boxstarter was being used in this context, and the small amount of testing that was done prior to it shipping.

I don't know if you saw them, but I created a couple of videos that show the entire installation process of Node JS, using Boxstarter, and it does work:

https://youtu.be/gwFpXXIJTvs
https://youtu.be/OgJBFSfsRP0

However, there are lots of edge cases, and things that can happen, that result in some of the things that you mention in your first post.

**Comment by kirannhegde** [comment] 2020-12-19 05:00
I agree with @gep13 and @flcdrg. Boxstarter is awesome. It's used extensively within our organization and combines it with an internal chocolatey feed, it excels at what it's designed for.  I can vouch for BoxStarter on any given day.
