### ISSUE TITLE
Website Navbar links don't work

### ISSUE THREAD

**Issue by gbloice** [chocolatey/boxstarter#314] opened 2018-06-02 08:18 UTC
As per the title, using Chome 67.

None of the navbar "links" actually function as a link except the one for the current page.

**Comment by gep13** [comment] 2018-06-05 09:20
@gbloice can you clarify that you are referring to the `Docs`, `Learn` `Issues` etc links along the top of the page?

![image](https://user-images.githubusercontent.com/1271146/40967066-0b9b701e-68aa-11e8-8f2b-13aabd653a6f.png)

If so, I have just tried all of them, and they all appear to function as expected.

**Comment by gbloice** [comment] 2018-06-07 08:28
Nope, the items in the vertical listbox:

![boxstarter](https://user-images.githubusercontent.com/3820413/41087590-03177abe-6a35-11e8-8741-208ab194ee04.PNG)

However, I've just checked again, admittedly on a different machine and they're working there.  I'll recheck on the original machine tonight.

**Comment by gep13** [comment] 2018-06-07 09:40
@gbloice if you could, that would be great.  I am just testing each of those links here with me as well, and they all seem to be working as expected.

**Comment by gbloice** [comment] 2018-06-08 20:41
I've worked out what happens, if you reduce the browser window width, at a certain size the navbar links jump into the page body, the body text flows around them, but they no longer function as links.

**Comment by pauby** [comment] 2018-08-05 19:03
Confirmed this doesn't work - links are available at the small bowser width but they are not clickable.

**Comment by pauby** [comment] 2019-03-19 00:01
Duplicate of #120.

**Closed by pauby** 2019-03-19 00:01 UTC
Labels: Duplicate Issue
