### ISSUE TITLE
Allow setting UAC level

### ISSUE THREAD

**Issue by AnthonyMastrean** [chocolatey/boxstarter#298] opened 2018-01-17 20:37 UTC
There's more to UAC than just on/off, but, apparently, the [solution](https://superuser.com/a/817117/1739) is complicated.

![image](https://user-images.githubusercontent.com/217842/35065788-499c6e8e-fb9c-11e7-94b0-4efe48955510.png)

**Comment by pauby** [comment] 2019-03-18 23:49
Duplicate of #47

**Closed by pauby** 2019-03-18 23:49 UTC
Labels: Duplicate Issue
