### ISSUE TITLE
Error while trying to install boxstarter

### ISSUE THREAD

**Issue by bhaizlett123** [chocolatey/boxstarter#406] opened 2019-10-02 12:45 UTC
### What You Are Seeing?
PS C:\Users\admin\Desktop\BOXSTARTER\Boxstarter.2.12.0> {Invoke-WebRequest -useb http://boxstarter.org/bootstrapper.ps1} | Invoke-Expression; Get-Boxstarter -Force

StatusCode        : 200
StatusDescription : OK
Content           : function Get-Boxstarter {
                        Param(
                            [string] $Version = "2.12.0",
                            [switch] $Force
                        )
                        if(!(Test-Admin)) {
                            $bootstrapperFile = ${function:Get-Boxstarter}.File
                        ...
RawContent        : HTTP/1.1 200 OK
                    Transfer-Encoding: chunked
                    Connection: keep-alive
                    Vary: Accept-Encoding
                    Content-Type: text/plain
                    Date: Wed, 02 Oct 2019 12:36:15 GMT
                    ETag: W/"8bacbd86670d41:0"
                    Last-Modified: Tu...
Forms             :
Headers           : {[Transfer-Encoding, chunked], [Connection, keep-alive], [Vary, Accept-Encoding], [Content-Type, text/plain]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        :
RawContentLength  : 5811

Welcome to the Boxstarter Module installer!
Chocolatey installed, Installing Boxstarter Modules.
Chocolatey v0.10.15
Installing the following packages:
Boxstarter
By installing you accept licenses for the packages.
Boxstarter not installed. An error occurred during installation:
 The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Boxstarter package files install completed. Performing other installation steps.
The install of Boxstarter was NOT successful.
Boxstarter not installed. An error occurred during installation:
 The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - Boxstarter (exited 1) - Boxstarter not installed. An error occurred during installation:
 The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Import-Module : The specified module 'C:\ProgramData\boxstarter\boxstarter.chocolatey\boxstarter.chocolatey.psd1' was not loaded because no
valid module file was found in any module directory.
At C:\Users\admin\Desktop\BOXSTARTER\Boxstarter.2.12.0\bootstrapper.ps1:41 char:9
+         Import-Module "$env:ProgramData\boxstarter\boxstarter.chocola ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\ProgramData\...chocolatey.psd1:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

Boxstarter Module Installer completed

PS C:\Users\admin\Desktop\BOXSTARTER\Boxstarter.2.12.0>
### What is Expected?

To install boxstarter successfully

### How Did You Get This To Happen? (Steps to Reproduce)
Install windows pro 10
Went through the instructions to install boxstarter

Error while installing

**Comment by pauby** [comment] 2019-10-02 12:52
Where did you get the installation command ` {Invoke-WebRequest -useb http://boxstarter.org/bootstrapper.ps1} | Invoke-Expression; Get-Boxstarter -Force` from?

**Comment by AdmiringWorm** [comment] 2019-10-02 12:54
@pauby I assume he got it from https://boxstarter.org/InstallBoxstarter

![image](https://user-images.githubusercontent.com/1474648/66045706-8be2f100-e524-11e9-84db-0b09ec7cfae8.png)

**Comment by bhaizlett123** [comment] 2019-10-02 12:55
that is correct

**Comment by pauby** [comment] 2019-10-02 12:55
@AdmiringWorm I thought the same. But the code being run and the code on that page are not the same.

**Comment by pauby** [comment] 2019-10-02 12:58
@bhaizlett123 You've missed the dot at the beginning. Using your code, you need to run `. {Invoke-WebRequest -useb http://boxstarter.org/bootstrapper.ps1} | Invoke-Expression; Get-Boxstarter -Force` or copy and paste the code from the install page - `. { iwr -useb https://boxstarter.org/bootstrapper.ps1 } | iex; Get-Boxstarter -Force`

**Comment by bhaizlett123** [comment] 2019-10-02 12:59
I tried that and get the same error

PS C:\Users\admin\Desktop\BOXSTARTER\Boxstarter.2.12.0> . {Invoke-WebRequest -useb http://boxstarter.org/bootstrapper.ps1} | Invoke-Expression; Get-Boxstarter
Welcome to the Boxstarter Module installer!
Chocolatey installed, Installing Boxstarter Modules.
Chocolatey v0.10.15
Installing the following packages:
Boxstarter
By installing you accept licenses for the packages.
Boxstarter not installed. An error occurred during installation:
 The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Boxstarter package files install completed. Performing other installation steps.
The install of Boxstarter was NOT successful.
Boxstarter not installed. An error occurred during installation:
 The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - Boxstarter (exited 1) - Boxstarter not installed. An error occurred during installation:
 The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Import-Module : The specified module 'C:\ProgramData\boxstarter\boxstarter.chocolatey\boxstarter.chocolatey.psd1' was not loaded because no
valid module file was found in any module directory.
At line:41 char:9
+         Import-Module "$env:ProgramData\boxstarter\boxstarter.chocola ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\ProgramData\...chocolatey.psd1:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by pauby** [comment] 2019-10-02 13:00
What version of .NET do you have installed?

**Comment by bhaizlett123** [comment] 2019-10-02 13:05
4.7

**Comment by bhaizlett123** [comment] 2019-10-02 13:24
is that version supported?

**Comment by pauby** [comment] 2019-10-02 13:44
I have just run `. {Invoke-WebRequest -useb http://boxstarter.org/bootstrapper.ps1} | Invoke-Expression; Get-Boxstarter -Force` here in a Windows 10 sandbox and it worked fine. I also did the same on a Windows Server 2012 R2 server with .NET 4.5.1 installed and again it worked fine.

So I can't reproduce the issue.

Are you going / should you be going through a proxy?

**Comment by bhaizlett123** [comment] 2019-10-02 13:51
No proxy at all, maybe I should try to uninstall .NET 4.7 and install 4.5, what do you think?

**Comment by pauby** [comment] 2019-10-02 15:26
I'd leave the .NET version as is. .NET 4.7 has everything that .NET 4.5 has. 

I genuinely think this is a local problem either on your machine or more likely your connection. Unfortunately I can't replicate it!

**Comment by bhaizlett123** [comment] 2019-10-02 15:44
could it be an issue with one of the certificates, i tried to install the comodo root cert and godaddy root cert and still not able to

**Comment by pauby** [comment] 2019-10-02 15:47
I wouldn't imagine so but it was worth a try.

@gep13 @AdmiringWorm Any suggestions?

**Comment by bhaizlett123** [comment] 2019-10-02 15:49
i tried that, but that didn't work, and don't have any proxy or anything in the middle that would block that

**Comment by bhaizlett123** [comment] 2019-10-02 15:50
Where can i find the psd1 file that its looking for and maybe manually put it in

**Comment by bhaizlett123** [comment] 2019-10-02 15:54
ok i just created the directory and the file that is was complaining about it couldn't find and now i am getting this error

Failures
 - Boxstarter (exited 1) - Boxstarter not installed. An error occurred during installation:
 The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Import-Module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:41 char:9
+         Import-Module "$env:ProgramData\boxstarter\boxstarter.chocola ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by bhaizlett123** [comment] 2019-10-02 17:04
I just tried to set the powershell -Version 2

and i ran the script and now i get this error

Failures
 - Boxstarter - Boxstarter not installed. The package was not found with the source(s) listed.
 Source(s): 'https://www.myget.org/F/fireeye/api/v2;https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Version was specified as '2.12.0'. It is possible that version
 does not exist for 'Boxstarter' at the source specified.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.
Import-Module : The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At C:\Users\admin\Desktop\BOXSTARTER\Boxstarter.2.12.0\bootstrapper.ps1:41 char:9
+         Import-Module "$env:ProgramData\boxstarter\boxstarter.chocola ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

when i got to that url manually i get an error maybe that url is not working or something is weird with it.

**Comment by AdmiringWorm** [comment] 2019-10-02 19:02
> I wouldn't imagine so but it was worth a try.
> 
> @gep13 @AdmiringWorm Any suggestions? This isn't really a Boxstarter issue per se.

Unfortunately not, usually when I have seen that TLS exception (`The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.`) it is usually due to the request being modified (either by something on the computer, a proxy, the network provider, etc), or that the certificate have been revoked/expired (which I don't believe to be the case, as there would be quite a few other people that would experience the same problem in that case).
There could probably be a dozen other cases where this could happen as well though, although I am not familiar with what those cases would be.

To troubleshoot/fix that is unfortunately outside of my skills 😢

**Comment by AdmiringWorm** [comment] 2019-10-02 19:05
Wait a minute, that last failure that you are getting may be a small clue.

@bhaizlett123 
I see you got two sources listed in your last comment, one without a protocol (which means it uses http by default, thus no TLS/SSL). Just to make sure that isn't the problem, could you try either removing that source, or update it to have `https://`. (I can never remember if chocolatey only supports secure transactions on package apis or not).

**Comment by pauby** [comment] 2019-10-03 17:07
As this is not a Boxstarter issue I'm going to go ahead and mark it as such.

**Comment by pauby** [comment] 2020-01-29 11:05
There has been no update on this for some time so going to go ahead and close it.

**Closed by pauby** 2020-01-29 11:05 UTC
Labels: Not Issue / Cant Repro / Not Implement / Invalid
