### ISSUE TITLE
Update Boxstarter WinConfig Features Documentation "Set-WindowsExplorerOptions" - List detailed descriptions of command line parameters

### ISSUE THREAD

**Issue by gunther3613** [chocolatey/boxstarter#431] opened 2020-05-08 17:53 UTC
When looking at the documentation site for Set-WindowsExplorerOptions and Set-BoxstarterTaskbarOptions on the "Boxstarter WinConfig Features"(https://boxstarter.org/WinConfig) it lists the parameters but doesn't include a detailed description of what each parameter does. All the parameters descriptions are documented in the Powershell script file but not on the website.

It would be nice to have all the parameters described in detail on the website documentation section.

**Comment by pauby** [comment] 2020-05-10 12:27
Duplicate of #388

**Closed by pauby** 2020-05-10 12:27 UTC
Labels: Duplicate Issue
