### ISSUE TITLE
autologin doesn't work

### ISSUE THREAD

**Issue by amaau** [chocolatey/boxstarter#279] opened 2017-07-29 17:04 UTC
Autologin feature doesn't seem to work. (Testing on vm, on super fresh windows, from bootstrapper)
```
$cred = Get-Credential $env:username
Install-Boxstarterpackage -PackageName d:\a.txt -Credential $cred
```
a.txt is just
```
Disable-UAC
if (Test-PendingReboot) { Invoke-Reboot }
```
this restarts and asks for password

**Comment by flatlinebb** [comment] 2017-08-25 15:48
Apparently, this is the correct syntax for the credentials:
Install-Boxstarterpackage -PackageName d:\a.txt -Credential (Get-Credential username)

This will create a pop-up prompt for username and password.
Not sure if it will take the "$env:username" variable, would require testing.

**Comment by pauby** [comment] 2019-03-18 23:38
Duplicate of #318.

**Closed by pauby** 2019-03-18 23:38 UTC
Labels: Duplicate Issue
