### ISSUE TITLE
Cannot install Firefox with Boxstarter - extraction fails with can not open output file

### ISSUE THREAD

**Issue by Oxymoron290** [chocolatey/boxstarter#355] opened 2018-10-14 16:25 UTC
I am unable to install Firefox using Boxstarter with the command `cinst -y firefox`. I get a pop-up error  titled "Extraction Filed" with the message "Can not open output file". This halts execution until somebody manually clicks "OK". Firefox does not get installed. Running the same command with chocolaty installed has no problem, but it seems I'm unable to automate this.

![image](https://user-images.githubusercontent.com/2234419/46919322-6cfdee80-cfa3-11e8-9f2f-53abb50c2a24.png)

**Comment by pauby** [comment] 2019-03-19 00:22
@Oxymoron290 Did you ever manage to resolve this?

**Comment by Oxymoron290** [comment] 2019-03-25 00:19
Yes, I had to change the cache location of my installs

**Comment by Oxymoron290** [comment] 2019-03-25 00:19
it had something to do with the pathway being over 256 chars

**Comment by flcdrg** [comment] 2019-03-25 01:28
This is a duplicate of https://github.com/chocolatey/boxstarter/issues/241  - the chocolatey\chocolatey\chocolatey\... bit in the download path is the clue.

Please reopen if you think it's different.

**Closed by flcdrg** 2019-03-25 01:28 UTC
Labels: Duplicate Issue
