### ISSUE TITLE
Some Chocolatey packages are not unattended-installed

### ISSUE THREAD

**Issue by C-Duv** [chocolatey/boxstarter#181] opened 2016-05-16 15:10 UTC
Around Boxstarter version 2.8 some chocolatey packages failed to _unattended-install_ when running my "install-my-workstation" package.

Here is my "choco install" part:

``` Powershell
choco install LinkShellExtension
choco install myuninst
choco install shrewsoftvpn --installargs "/STANDARD /NODESK"
choco install nitroreader.install
choco install libreoffice
choco install PDFCreator --overridearguments --installargs "/VERYSILENT /NORESTART /COMPONENTS='program,ghostscript,languages,languages\french'"
choco install PDFsam.install
choco install filezilla
choco install chromium
choco install firefox --forcex86
choco install thunderbird
choco install consolez
choco install curl
choco install everything
choco install produkey.install
choco install win32-openssh -params="/SSHServerFeature"
choco install windirstat
```

From that list, the following software's installers are run in the foreground / GUI: local/keyboard user **have** to click on the standard installer's "next" buttons:
- PDFsam
- FileZilla
- Firefox
- Thunderbird
- Everything
- WinDirStat

(I am running Boxstarter v2.8.12 on Windws 7)

[Here is the Boxstarter.log around PDFSam and FileZilla](https://gist.github.com/C-Duv/7612529fae13cf422695079e98f2837f).

Running `choco install -y pdfsam.install` manually works just fine (PDFsam in install without user interaction).

**Comment by mwrock** [comment] 2016-05-22 01:24
I was not able to reproduce this problem. I dont have a win7 vm handy but I did try on win2008R2 which is essentially the same core. I installed via the web boxstarter installer (http://boxstarter.org/package/filezilla) and tried filezilla, pdfsam and windirstat.

**Comment by pauby** [comment] 2019-03-18 21:08
No updates in some time and not able to reproduce the issue. Going to go ahead and close this but we can reopen in the future if needed.

**Closed by pauby** 2019-03-18 21:08 UTC
Labels: Not Issue / Cant Repro / Not Implement / Invalid
