### ISSUE TITLE
Get-Boxstarter fails to install Chocolatey on PowerShell 7

### ISSUE THREAD

**Issue by MisinformedDNA** [chocolatey/boxstarter#467] opened 2021-01-28 15:02 UTC
### What You Are Seeing?

Get-Boxstarter fails to install Chocolatey on PowerShell 7

### What Is Expected?

Get-Boxstarter runs successfully.

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
PS C:\Windows\System32> . { iwr -useb https://boxstarter.org/bootstrapper.ps1 } | iex; Get-Boxstarter -Force -debug -verbose
Welcome to the Boxstarter Module installer!
Chocolatey is going to be downloaded and installed on your machine. If you do not have the .NET Framework Version 4 or greater, that will also be downloaded and installed.
Did not detect Chocolatey and unable to install. Installation of Boxstarter has been aborted.

PS C:\Windows\System32> Check-Chocolatey -Force
Chocolatey is going to be downloaded and installed on your machine. If you do not have the .NET Framework Version 4 or greater, that will also be downloaded and installed.
False

PS C:\Windows\System32> $wc=new-object net.webclient
>> $wp=[system.net.WebProxy]::GetDefaultProxy()
MethodInvocationException:
Line |
   2 |                  $wp=[system.net.WebProxy]::GetDefaultProxy()
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "GetDefaultProxy" with "0" argument(s): "Operation is not supported on this platform."
~~~

</p>

</details>

**Comment by flcdrg** [comment] 2021-01-30 23:02
Probably a duplicate of #353

**Closed** 2021-02-01 13:58 UTC
Labels: Duplicate Issue
