### ISSUE TITLE
Doesn't log on using the correct computer name after renaming computer

### ISSUE THREAD

**Issue by illectronic** [chocolatey/boxstarter#260] opened 2017-05-17 17:27 UTC
I am renaming the computer and I am passing this for username in the pscredential: new-computer-name\administrator but according to the logs it is storing it as:

[2017-05-17T17:21:04.5294000+00:00:::PID 800] Boxstarter: Securely Storing old-computer-name\Administrator credentials for automatic logon

Is there a way to get around this when launching install-boxstarterscript?

**Comment by pauby** [comment] 2019-03-18 23:33
Duplicate of #233.

**Closed by pauby** 2019-03-18 23:33 UTC
Labels: Duplicate Issue
