### ISSUE TITLE
Uninstall "left overs"

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/boxstarter#336] opened 2018-08-14 17:18 UTC
### What You Are Seeing?

After uninstalling boxstarter and modules the start menu icon hasn't been deleted and boxstarter is still in the path.

![image](https://user-images.githubusercontent.com/14026600/44107174-55564e44-9fab-11e8-8854-5b8f495d2ea6.png)

![image](https://user-images.githubusercontent.com/14026600/44107051-093cf7e2-9fab-11e8-8dd9-756aedbfc732.png)

### What is Expected?

Boxstarter to remove these items during uninstall.

### How Did You Get This To Happen? (Steps to Reproduce)
choco uninstall:
Boxstarter.Bootstrapper
Boxstarter.Chocolatey
Boxstarter.Common
Boxstarter.HyperV
Boxstarter.WinConfig

**Comment by zgf138** [comment] 2018-11-09 01:30
How to uninstall in win10?

**Comment by pauby** [comment] 2018-11-09 09:19
@zgf138 Boxstarter is just a PowerShell module and is uninstalled depending on how you installed it - either using the normal method for working with PowerShell modules (Install-Module / Uninstall-Module) or using Chocolatey `choco uninstall`.

The best place for questions is [Gitter](https://gitter.im/chocolatey/boxstarter).

**Comment by ilyagrigoryev** [comment] 2018-11-14 17:17
the same
@pauby could you be more specific?

**Comment by pauby** [comment] 2018-11-14 17:36
@ilyagrigoryev If you installed it via Chocolatey then run:

```
'BoxStarter.Common', 'boxstarter', 'boxstarter.chocolatey', 'boxstarter.bootstrapper', 'Boxstarter.HyperV', 'BoxStarter.WinConfig', 'Boxstarter.Azure', 'Boxstarter.TestRunner', 'Boxstarter.WindowsUpdate' | % { choco uninstall $_ -y }
```

Or if you installed the modules use `get-module boxstarter* -li | uninstall-module` it should remove the PowerShell modules. 

If there are any shortcuts you will have to remove them separately.

**Comment by stacktracer** [comment] 2018-11-19 14:33
I'm struggling with this as well. For context, I ended up here by running the Node.js MSI installer -- it installed boxstarter and chocolatey (among other things), then failed and aborted, and now I'm trying to undo the mess it left.

I ran `choco uninstall` for each boxstarter package. Each one printed a failure message -- at first because dependent packages were still installed, and then when I tried again, because none of the packages were found. So did they uninstall or not? I can't tell. They don't show up in `choco list --local-only`, but `C:\ProgramData\Boxstarter` and its subdirs are all still there in the filesystem.

I then ran the suggested PowerShell module commands, but got errors from `uninstall-module`, and as before `C:\ProgramData\Boxstarter` and its subdirs are still around:
```
PS C:\WINDOWS\system32> get-module boxstarter* -li


    Directory: C:\ProgramData\Boxstarter


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.12.0     Boxstarter.Bootstrapper             {Enter-BoxstarterLogable, Get-BoxstarterTempDir, Invoke-Reboot, Stop-TimedSection...}
Script     2.12.0     Boxstarter.Chocolatey               {Set-BoxstarterShare, Get-PackageRoot, Register-ChocolateyInterception, Invoke-ChocolateyBoxstarte...
Script     2.12.0     Boxstarter.Common                   {Get-HttpResource, Remove-BoxstarterTask, Get-IsRemote, Enter-BoxstarterLogable...}
Script     2.12.0     Boxstarter.HyperV                   {Enable-BoxstarterVHD, Enable-BoxstarterVM, Get-HttpResource, Remove-BoxstarterTask...}
Script     2.12.0     Boxstarter.WinConfig                {Disable-GameBarTips, Disable-MicrosoftUpdate, Enable-RemoteDesktop, Set-StartScreenOptions...}


PS C:\WINDOWS\system32> get-module boxstarter* -li | uninstall-module
PackageManagement\Uninstall-Package : No match was found for the specified search criteria and module names 'Boxstarter.Bootstrapper'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2194 char:21
+ ...        $null = PackageManagement\Uninstall-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Package], Exception
    + FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage

PackageManagement\Uninstall-Package : No match was found for the specified search criteria and module names 'Boxstarter.Chocolatey'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2194 char:21
+ ...        $null = PackageManagement\Uninstall-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Package], Exception
    + FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage

PackageManagement\Uninstall-Package : No match was found for the specified search criteria and module names 'Boxstarter.Common'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2194 char:21
+ ...        $null = PackageManagement\Uninstall-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Package], Exception
    + FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage

PackageManagement\Uninstall-Package : No match was found for the specified search criteria and module names 'Boxstarter.HyperV'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2194 char:21
+ ...        $null = PackageManagement\Uninstall-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Package], Exception
    + FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage

PackageManagement\Uninstall-Package : No match was found for the specified search criteria and module names 'Boxstarter.WinConfig'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2194 char:21
+ ...        $null = PackageManagement\Uninstall-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Package], Exception
    + FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage
```

**Comment by pauby** [comment] 2018-11-19 17:09
@stacktracer What OS are you running on? What is the output of `Get-PackageProvider`

**Comment by tuaminen** [comment] 2018-11-19 17:48
> @stacktracer What OS are you running on? What is the output of `Get-PackageProvider`

Hi, I also installed Node.js 10 with native support, and ran into problems with my Windows 10. After installing Node.js, Skype and Store no longer function.

So I am now trying to revert everything, and I get the same error as stacktracer above mentions.

My OS is Windows 10 Home N, version 1803 Build 17134.407.

PS C:\WINDOWS\system32> Get-PackageProvider

Name                     Version          DynamicOptions
----                     -------          --------------
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
PowerShellGet            1.0.0.1          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, ...
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent

Any help is welcome!

**Comment by stacktracer** [comment] 2018-11-19 18:40
Win10 Enterprise, 64-bit, Version 1803 Build 17134.407

```
PS C:\Users\mike> Get-PackageProvider | out-string -width 300

Name                     Version          DynamicOptions                                                                                                                                                                                                     
----                     -------          --------------                                                                                                                                                                                                     
msi                      3.0.0.0          AdditionalArguments
msu                      3.0.0.0
PowerShellGet            1.0.0.1          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, Filter, Tag, Includes, DscResource, RoleCapability, Command, PublishLocation, ScriptSourceLocation, ScriptPublishLocation
Programs                 3.0.0.0          IncludeWindowsInstaller, IncludeSystemComponent
```

**Comment by swissarm** [comment] 2018-11-21 07:11
Hi, I have the same problem, 

Here is what I did, 

1. Go to C:\Program Data
2. You will see Boxstarter & Chocolatey Folder
3. Delete both of them

If there is still left overs when you searching through windows menu, so just right click the icon, and open file location, delete the shorcut. Restart your computer.

**Comment by AdmiringWorm** [comment] 2018-11-21 17:33
@swissarm you probably still have a couple of left-overs from chocolatey.
Two environment variables called: `ChocolateyInstall` and `ChocolateyLastPathUpdate`, as well as having the path to where chocolatey was installed to in the `PATH` environment variable. (Same with the path to boxstarter directory, in `PATH`)

Oh, and don't forget the `PSModulePath` environment variable which also have the boxstarter directory added to it.

**Comment by swissarm** [comment] 2018-11-22 09:10
@AdmiringWorm you are right there are still a couple of left-overs from it.  I will remove it later. 
The most important thing for me here is the boxstarter auto update won't working because I have already remove the main folder. 
Thank a lot man !

**Comment by Zeus64** [comment] 2018-11-22 09:39
same for me, my system is just a mess now :( :( :(

**Comment by bcurran3** [comment] 2018-11-22 11:57
I would suggest reinstalling Chocolatey and then Boxstarter if you're trying to make them both work again.

Chocolatey can be re-installed over itself over and over and over again without worries.

**Comment by Zeus64** [comment] 2018-11-22 12:03
no i don't want to install, i want to uninstall. my system is now completely unstable/broken after trying to uninstall Chocolatey and boxstarter :(

**Comment by bcurran3** [comment] 2018-11-22 13:02
Can you let us know some of the symptoms and maybe we can help.  
I really can't see however moving either of these could cause what you describe.

**Comment by anupamsr** [comment] 2018-11-22 14:08
Basically Boxstarter folder isn't removed from ProgramData. Deleting the whole folder fixed the problem with unnecessary modules in powershell. After which I deleted the shortcuts.

**Comment by funky81** [comment] 2018-11-24 14:29
> no i don't want to install, i want to uninstall. my system is now completely unstable/broken after trying to uninstall Chocolatey and boxstarter :(

Similiar like @Zeus64 , what i want to do just install npm..then I go to this mess 
My Windows 10 so unstable right now with disk usage always 100%

**Comment by pauby** [comment] 2018-11-24 14:37
> My Windows 10 so unstable right now with disk usage always 100%

@Zeus64 I'm surprised that Chocolatey / Boxstarter are pegging your CPU at 100%. What is task manager saying?

**Comment by Zeus64** [comment] 2018-11-24 14:55
@pauby cpu is not 100% but my system is now just a mess! this chocolatey / Boxtarter are really not professionally made :( I will also complain with nodeJS team as it's them who install it (and of course let all this mess in the system when we uninstall NodeJS). really not serious!

**Comment by pauby** [comment] 2018-11-24 15:02
> My Windows 10 so unstable right now with disk usage always 100%

@Zeus64 Apologies. Your disk is at 100% - what is causing this? What does Task Manager tell you?

> this chocolatey / Boxtarter are really not professionally made :(

That's not helping us help you. Bear in mind the NodeJs installer does ask you two / three times whether you want to install Chocolatey and Boxstarter so you did have the opportunity to not proceed.

And you've still not actually told us what is wrong - 'is a mess' tells us nothing. You've posted several messages now about your system being in a 'mess'. People have responded to you but you don't appear to be taking the advice - at least you're not telling us anything different so I'm assuming you've not taken it as you don't appear to be moving forward.

Have you followed the instructions to remove Chocolatey and Boxstarter? No, then please do so. Yes, then please tell us **exactly** what you have done and anything else you have done.

**Comment by Zeus64** [comment] 2018-11-24 16:03
@pauby : I agree with you, but I m so must disgusted that I lost my clean system that I miss my "diplomatic" behavior :( I sorry for that !

I first uninstall NodeJS, then I see that many stuff are still in my system like Chocolatey, Boxstarter, visual studio stuff,some dll also in the windows system (this why I will also need to speak with NodeJS team, but that another problem). So I try to uninstall manually Chocolatey and Boxstarter in the way they will also delete all the mess with dll/visual studio they put everywhere in my system. I do some command like "chocolatey uninstall <packageName>" and boom now nothing work well in my system. Even photoshop refuse to start now :(

Really I was not aware that it's could be so dangerous to install NodeJS :(

**Comment by DoCode** [comment] 2018-11-24 16:31
So guys, I'm with @Zeus64...
I'm also think tools like boxstarter and chocolatey, which install so many things with scripting methodics (like UAC on, off, reboot, KB's here an there and no clear uninstall), should NOT be installed with frameworks like NodeJS.

**Comment by pauby** [comment] 2018-11-24 17:37
@zeus64 

> "chocolatey uninstall packageName"

That again doesn't help. Which package did you uninstall? Why did you uninstall it (were you told to, did you guess, etc.)?

> Even photoshop refuse to start now :(

What error are you getting with this?

> Really I was not aware that it's could be so dangerous to install NodeJS :(

As I said before you were given two opportunities not to install Chocolatey and Boxstarter with NodeJs. I absolutely appreciate this doesn't help you but what I am personally annoyed about is the amount of time we have spent troubleshooting issues with the NodeJs installer and we have to let anybody else know in this thread about that.

I've said several times, and again I know I'm labouring the point, but you need to follow the advice in this thread to remove Chocolatey and Boxtstarter. You need to stop trying to fix it yourself as it's clear, with all due respect, that you are not familiar with them.

However the damage you said has been done I cannot see either of those doing.

**Comment by pauby** [comment] 2018-11-24 17:39
@DoCode I actually agree with you. However you will need to take that up with the NodeJs team. We were not aware they were using it until issues started being raised in here. See https://github.com/nodejs/node/issues/23838

However this issue is not around this. It's around uninstalling leftovers.

**Comment by DoCode** [comment] 2018-11-24 17:41
@pauby sorry for the breakdown here.

**Comment by alincosmin7** [comment] 2018-11-25 09:07
@pauby the problem is there is not just a folder to delete, looking into log i have many additional things installed. Also, I don't understand why automatic updates are disabled, what happens if the rest of the script will fail? 

When installing the node.js with the windows installer, the option to install boxstarter and chocolatey is giving you the impression that this are some tools required for node.js to work, no one tells you that visualstudio2017buildtools and vc_redist.x86.exe will be installed, perhaps it is something that i don't want. Another annoying thing is that during the installation the computer restarts automatically without giving you the time to save your work.

In conclusion, I don't see a way to revert this, other than take the log and do everything manually 

See here some lines from my install log:

_Boxstarter: Disabling Automatic Updates from Windows Update...
Upgrading the following packages:
;visualstudio2017buildtools
By upgrading you accept licenses for the packages.
visualstudio2017buildtools v15.9.1.0 is the latest version available based on your source(s).
KB3035131 v1.0.2 [Approved]
kb3035131 package files upgrade completed. Performing other installation steps.
Skipping installation because update KB3035131 does not apply to this operating system (Microsoft Windows 10 Pro N).
Skipping installation because update KB3035131 does not apply to this operating system (Microsoft Windows 10 Pro N).
 The upgrade of kb3035131 was successful.
Download of vc_redist.x86.exe (13.83 MB) completed.
Hashes match.
Installing vcredist140-x86..._

**Comment by Zeus64** [comment] 2018-11-25 09:47
@pauby I too really appreciate your help and your patience, even if I m very upset about the situation.

To go further with what @alincosmin7 say, in my case the process, 

> Boxstarter: Disabling Automatic Updates from Windows Update...
> Upgrading the following packages:
> ;visualstudio2017buildtools
> By upgrading you accept licenses for the packages.
> visualstudio2017buildtools v15.9.1.0 is the latest version available based on your source(s).
> ...

With really I was not aware of all the process when I check the checkbox "install boxstarter and chocolatey", I was thinking is just some extra binary that will be put in the NodeJS directory, I never imagine one minute that my system will be HARDLY (not even leaving me the choice to close and save my current work) rebooted several time! I can even not believe that this [@[{^{[ (sorry i m really too much upset) will even install windows KB!! what this hell that installs KB's in my back without asking me! I have many other tools that run on my system, I can not update it like this! At the end of all of this I saw also many error messages. I don't know If my system becomes unstable because of the install process or because I uninstall everything.

> Even photoshop refuse to start now :(
> > What error are you getting with this?

Asking me to set my registration again :( maybe it's detected some change in my system and invalidate the previous registration (that I did in 2014, so 5 years ago, and I never had any problem before I install/uninstall nodeJS)

**Comment by pauby** [comment] 2018-11-25 12:37
@alincosmin7

> the problem is there is not just a folder to delete, looking into log i have many additional things installed. 

There will be many additional things installed by the script that installs NodeJs. You will have additional KB's installed, visualstudiobuildtools etc. (the KB's are necessary to for the visualstudiobuildtools to install). These are installed by the script that NodeJs asks Boxstarter to run. So note that Boxstarter is only doing as it is told.

> Also, I don't understand why automatic updates are disabled, what happens if the rest of the script will fail?

Boxstarter disables Windows Updates (as you don't want Windows to go off and install updates while it is running). If the Boxstarter fails then it's not going to enable those updates again. If you still have Boxstarter.WinConfig module installed you can try using `Enable-WindowsUpdate`?

> When installing the node.js with the windows installer, the option to install boxstarter and chocolatey is giving you the impression that this are some tools required for node.js to work, no one tells you that visualstudio2017buildtools and vc_redist.x86.exe will be installed, perhaps it is something that i don't want. 

I don't use NodeJs so I can't comment on whether those are required tools are required or not but they are [certainly installed](https://github.com/nodejs/node/blob/master/tools/bootstrap/windows_boxstarter).

> Another annoying thing is that during the installation the computer restarts automatically without giving you the time to save your work.

Boxstarter was originally put together to allows bare OS boxes to be bootstrapped, installing all the software and features that are needed. So it was originally intended for unintended install and during that unattended install you're going to be annoyed when you pop back to see the computer only 5% through sitting waiting to be rebooted. So Boxstarter does that automatically when it detects a reboot is required.

On the NodeJs screen it doesn't specifically mention that a reboot will be done.

![https://user-images.githubusercontent.com/1271146/47272399-00738880-d57d-11e8-9de6-0a6b86df7dac.png]

https://github.com/nodejs/node/pull/23987 was raised to cover explicitly saying that a reboot will occur and UAC will be disabled.

> In conclusion, I don't see a way to revert this

I've asked other to confirm that they have followed the advice in this thread. Have you done that? If so what are the issues that you are still seeing (specifically)?

**Comment by pauby** [comment] 2018-11-25 12:47
@Zeus64 
> With really I was not aware of all the process when I check the checkbox "install boxstarter and chocolatey", I was thinking is just some extra binary that will be put in the NodeJS directory, I never imagine one minute that my system will be HARDLY (not even leaving me the choice to close and save my current work) rebooted several time!

I get you. I would be annoyed too. I get everything you are saying. As I mentioned in my comment above, https://github.com/nodejs/node/pull/23987 has been raised with the NodeJs team to make this more explicit. That doesn't help you right now but it's an acknowledgement that they have taken that on-board.

> will even install windows KB!! what this hell that installs KB's in my back without asking me! I have many other tools that run on my system, I can not update it like this! 

I'm not sure why you are getting so upset about the KB's so perhaps I am missing something. The [NodeJs boxstarter script](https://github.com/nodejs/node/blob/master/tools/bootstrap/windows_boxstarter) installs:

* [git](https://chocolatey.org/packages/git)
* [python2](https://chocolatey.org/packages/python2)
* [visualstudio2017buildtools](https://chocolatey.org/packages/visualstudio2017buildtools)
* [visualstudio2017-workload-vctools](https://chocolatey.org/packages/visualstudio2017-workload-vctools)
* [nasm](https://chocolatey.org/packages/nasm)

For each one of those packages, you can scroll down on the links to 'Dependencies' and it will tell you what else those packages required (for example visualstudio2017buildtools requires chocolatey-visualstudio.extension, KB2919355, KB2999226, dotnet4.6.2 and visualstudio2017-installer so they will also be installed and each of those packages may also have dependencies). So you can follow back to see what has been installed. You can also go through Programs and Features and sort by the Installed Date).

> I don't know If my system becomes unstable because of the install process or because I uninstall everything.

I can't say if your system would become unstable but bear in mind all that is being done is disabling UAC and Windows Updates, installing some software and then re-enabling UAC and Windows Updates - that's assuming everything ran as it should. I can't see how it would make it unstable.

> Asking me to set my registration again :( maybe it's detected some change in my system and invalidate the previous registration (that I did in 2014, so 5 years ago, and I never had any problem before I install/uninstall nodeJS)

It could just be that. It could be coincidence. I can't make any rational connection between installing the software and that happening. That's not to say there isn't one.

**Comment by alincosmin7** [comment] 2018-11-25 13:36
@pauby , you are right. It is a problem on how Node.Js team choose to install additional tools, it is not related to boxstarter. Personally I had no issues with the installation.

**Comment by ferventcoder** [comment] 2018-11-26 23:51
@Zeus64 Your stuff doesn't work because you possibly interrupted Boxstarter or there was an edge case where it was not able to re-implement UAC. Once you turn UAC back on, those apps should start working. 
Basically anything from the Windows Store will refuse to run without UAC turned on. You absolutely can not shut it off except by a registry setting in Windows 10 for this reason. cc @pauby

**Comment by ferventcoder** [comment] 2018-11-26 23:55
>So guys, I'm with @Zeus64...
> I'm also think tools like boxstarter and chocolatey, which install so many things with scripting methodics (like UAC on, off, reboot, KB's here an there and no clear uninstall), should NOT be installed with frameworks like NodeJS.

@DoCode let me fix that for you. `s/and chocolatey/` 

> I'm also think tools like boxstarter ~~and chocolatey~~, which install so many things with scripting methodics (like UAC on, off, reboot, KB's here an there and no clear uninstall), should NOT be installed with frameworks like NodeJS.

And I agree with @pauby's comments above as well on this.

**Comment by BhagiLimbu** [comment] 2018-11-27 03:40
I wonder if you have similary issue as I'm facing now. After remove boxstarter and chocolatey from:
1) C:\ProgramData
2) Delete environment variables
3) Remove from powershall : PSModulePath

The boxstarter script still trying to run (trigger) from somewhere after restart PC on complete windows desktop initialization.  I've attached here screen capture for your reference. Appreciate, if you could share your experience to resolve this issue.

![boxstarter-startup-2](https://user-images.githubusercontent.com/6449113/49057085-18ec5800-f239-11e8-8fb8-0bec1465b1ad.png)

**Comment by pauby** [comment] 2018-11-27 08:58
@BhagiLimbu What that error is saying is that it can't find that file at that location. How did you get to that (did you just install NodeJs and do nothing else)?

My first question would be does the file exist at that location? Are any parts of the path there? Is your system drive C:?

Second question is did you remove anything?

**Comment by fenchu** [comment] 2018-11-27 13:07
Could someone please explain the rationale why this showed up as an option when installing nodejs 10.13.0 LTS (Long Term Support is for stable reliable). If you are a nodejs developer you're probably better off using pm2 and shell.js. for managing and starting stopping services (and it is linux compatible also). I saw the warning, but do not see why this have anything to do with nodejs at all. Is it sponsored?

**Comment by v3nxik** [comment] 2018-11-27 15:55
@BhagiLimbu i was facing the same problem with you and what i did was open task manager, go to startup tab, there should be file named with boxstarter, click right, go to file location and delete it

**Comment by BhagiLimbu** [comment] 2018-11-28 10:29
@pauby thanks for quick response. Yes I install with NodeJs and follow the instruction of @swissarm to uninstall from PC. Finally, I manage resolve issue as mention by @v3nxik (many thanks).

**Comment by funky81** [comment] 2018-11-28 23:13
One problem left for me is that Windows Update still disabled. How to enable it back?

**Comment by bcurran3** [comment] 2018-11-29 01:11
@20k, maybe this will help:

https://blogs.msdn.microsoft.com/powershell/2009/01/31/managing-windows-update-from-powershell/

**Comment by 20k** [comment] 2018-11-29 01:45
I tried reinstalling windows through windows system restore and the damage to windows update has managed to survive it. This is legitimately incredible, I'm amazed that the this is still being distributed in its current state as it looks like I might need to completely wipe windows to fix my pc because of a simple npm update. That link has not helped

**Comment by pauby** [comment] 2018-11-30 09:41
@20k Have you tried any of the other options suggested?

Another suggestion is `. (Join-Path -Path $env:ProgramData -ChildPath 'boxstarter\boxstarter.bootstrapper\start-updateservices.ps1'); start-updateservices`

**Comment by BhagiLimbu** [comment] 2018-12-04 08:16
@20k Does your windows update back? I have same problem, my windows update is disable. I click manually on "Check Of Updates" button several it does not work.

**Comment by Garfonso** [comment] 2018-12-07 17:33
I was lead here from #268.

Issue is still, information in this issue is incomplete. I had to write `choco uninstall boxstarter`. Only then I could select to uninstall all boxstartert stuff. After that there are still python and other stuff that boxstarter installed without asking me in the system.
Also the main issue is not resolved, https://boxstarter.org/WhyBoxstarter is still missing an explanation how to get rid of boxstarter.

Also after you got rid of boxstarter, there still is chocolatery on the system. But there is good news here, that project seems more mature and does not need to lock in its users. There is information on how to uninstall that here: https://chocolatey.org/docs/uninstallation

Sadly you closed the other issues. It still is the top match from google for boxstarter uninstall. So I would add this information in the original issue (or better: create an unistall doc page ASAP and make sure it gets top rank in google).
Also, if you create a desktop Icon, it is completely non understandable why you do not create one for uninstallation, at least in startmenu.

**Comment by Garfonso** [comment] 2018-12-07 17:44
I have to add to my last post: 
`choco uninstall boxstarter` does not work at all. Boxstarter is still there and doing strange stuff.

Background: As you might see I am a bit pissed. Reason: I was forced by a different software to log into my administrator account by a different software. Then a cmd windows popped up running some stuff from boxstarter and rebooting my laptop without asking or any notice. After logging in again a new cmd window opened again. And it still does and wants to install even more stuff.... even after running the proposed "uninstall" which is not working at all.

So please fix uninstall and add some easy to follow documentation on how to get rid of this stuff.
Also I do not know at all on how boxstarter got on my system in the beginning...

So all in all, the original issue is not fixed at all, athough your github issues does state otherwise. What is discussed in this issue is something completely different and might be interesting after the original issues was adressed (which is not the case). Also I can not see in this discussion any information about how to get rid of "dependencies" like divers python interpreters that boxstarter threw on my system (and is throwing again and again everytime the administrator account logs in).

**Comment by pauby** [comment] 2018-12-07 17:50
@Garfonso Let's clear this up.

> Issue is still, information in this issue is incomplete. I had to write choco uninstall boxstarter. Only then I could select to uninstall all boxstartert stuff.

The request to ask you to uninstall Boxstarter is [here](https://github.com/chocolatey/boxstarter/issues/336#issuecomment-438750339)

> After that there are still python and other stuff that boxstarter installed without asking me in the system.

Two points here:

1. If you installed Boxstarter yourself then it doesn't install Python. So that's a no.
2. If you installed NodeJs and got Boxstarter installed then you were asked [two / three times to confirm](https://github.com/chocolatey/boxstarter/issues/336#issuecomment-441373938). NodeJs does install [Python2](https://github.com/chocolatey/boxstarter/issues/336#issuecomment-441438048).

> Also the main issue is not resolved, boxstarter.org/WhyBoxstarter is still missing an explanation how to get rid of boxstarter.

That's not the main issue of this GitHub issue. If you want to suggest that be added then please raise an issue for an enhancement. We would also welcome any help putting that together so pull requests are welcome.

> Also after you got rid of boxstarter, there still is chocolatery on the system.

There is. Boxstarter installs Chocolatey. That is documented in the first sentence of the link you provided](https://boxstarter.org/WhyBoxstarter).

> But there is good news here, that project seems more mature and does not need to lock in its users. 

Can you confirm where and how Boxstarter locks in it's users?

> Sadly you closed the other issues.

I didn't close the other issue. [I locked it](https://github.com/chocolatey/boxstarter/issues/268#event-2012888928) to stop additional messages being added to it as it was [closed in 2017](https://github.com/chocolatey/boxstarter/issues/268#event-1150184990).

>  It still is the top match from google for boxstarter uninstall. So I would add this information in the original issue (or better: create an unistall doc page ASAP and make sure it gets top rank in google).

The other issue that you said ranks highly is linked to this one in the very [last comment](https://github.com/chocolatey/boxstarter/issues/268#issuecomment-445290755) after yours and the [one before it](https://github.com/chocolatey/boxstarter/issues/268#issuecomment-440977121). I'm not sure how clearer we could be.

As I suggested earlier if you want to open an issue for this we'd be happy to accept pull requests. 

> Also, if you create a desktop Icon, it is completely non understandable why you do not create one for uninstallation, at least in startmenu.

I agree. That's why we [fixed it](https://github.com/chocolatey/boxstarter/pull/372).

**Comment by pauby** [comment] 2018-12-07 17:56
@Garfonso 

> I have to add to my last post:
> choco uninstall boxstarter does not work at all. Boxstarter is still there and doing strange stuff.

It won't. You need to follow the steps in this thread. Please read it.

> So please fix uninstall and add some easy to follow documentation on how to get rid of this stuff.

Please see my previous message.

> Also I do not know at all on how boxstarter got on my system in the beginning...

You installed NodeJs (I assume?) and [agreed for it to be installed](https://github.com/chocolatey/boxstarter/issues/357#issuecomment-431705029).

The rest of your questions are answered elsewhere in this thread.

**Comment by Garfonso** [comment] 2018-12-07 21:01
@pauby 
Ok, I know did understand the necessary steps (for me this was a bit obscure, because I am not very familiar with PowerShell Syntax). And I now get what Boxstarter does. 
For me the whole issue was a bit more suprising than probably for other people, because the boxstarter script did not (or only partly) run, when I installed nodejs, which was about a month ago but only today. I think the reason for that is that I mostly work using a non-priviledge user account. Boxstarter started, as soon as I today logged into the administrator account. That probably is an issue in the node.js installer? (which was 10.13.0) Or is it by design and can not be fixed? It seems that after a reboot, I have to log into the administrator account again (which I normally don't) in order to continue the boxstarter script. So all the stuff that node.js wanted to have installed did not get installed at all until today.

**Comment by pauby** [comment] 2018-12-10 10:16
The original issue has been fixed in PR #372

**Closed by pauby** 2018-12-10 10:16 UTC
Labels: bug

**Comment by tiagozip** [comment] 2024-05-25 09:46
> For future people still struggling with this, I had success searching `boxstarter` using windows finder search and deleting all the instances associated with it.

The problem is that Windows Explorer's search is very, very slow.

**Comment by morsk** [comment] 2025-08-17 03:15
I just did this in 2025 and will document it. This is not from any weird installations with NodeJS. It is just installing with chocolatey, and not being able to uninstall cleanly.

1. Uninstall with choco. Order matters, as they depend on each other and won't remove if something depends on them.
choco uninstall Boxstarter
choco uninstall Boxstarter.HyperV
choco uninstall Boxstarter.Chocolatey
choco uninstall Boxstarter.Bootstrapper
choco uninstall Boxstarter.WinConfig
choco uninstall Boxstarter.Common

2. Delete folders.
Win+R -> %ProgramData% -> delete Boxstarter

3. edit system Path and PSModulePath to remove references to Boxstarter, particularly ProgramData\Boxstarter.
Win+R -> sysdm.cpl -> Advanced tab -> Environment Variables (button) -> bottom panel (System variables) -> edit Path and PSModulePath looking for entries with Boxstarter
(There are many ways to open this panel, but sysdm.cpl is the simplest one I know.)

Older posts mention Desktop & Start Menu shortcuts, but I had none. I believe that was fixed.

Regardless of the reason -- it's volunteer software -- it would be gaslighting if pretended that a process like this is normal. It is not normal.
